<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'PontosPassagem\Module'                        => __DIR__ . '/Module.php',
    'PontosPassagem\Controller\PontosPassagemController' => __DIR__ . '/src/PontosPassagem/Controller/PontosPassagemController.php',
    'PontosPassagemTest\Framework\TestCase'        => __DIR__ . '/tests/PontosPassagem/Framework/TestCase.php',
    'PontosPassagemTest\SampleTest'                => __DIR__ . '/tests/PontosPassagem/SampleTest.php',
);
