<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Percurso\Module'                        => __DIR__ . '/Module.php',
    'Percurso\Controller\PercursoController' => __DIR__ . '/src/Percurso/Controller/PercursoController.php',
    'PercursoTest\Framework\TestCase'        => __DIR__ . '/tests/Percurso/Framework/TestCase.php',
    'PercursoTest\SampleTest'                => __DIR__ . '/tests/Percurso/SampleTest.php',
);
