<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Turista\Module'                        => __DIR__ . '/Module.php',
    'Turista\Controller\TuristaController' => __DIR__ . '/src/Turista/Controller/TuristaController.php',
    'TuristaTest\Framework\TestCase'        => __DIR__ . '/tests/Turista/Framework/TestCase.php',
    'TuristaTest\SampleTest'                => __DIR__ . '/tests/Turista/SampleTest.php',
);
